<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXmvrhMx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXmvrhMx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXmvrhMx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXmvrhMx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXmvrhMx\App_KernelProdContainer([
    'container.build_hash' => 'XmvrhMx',
    'container.build_id' => '794bee80',
    'container.build_time' => 1743428744,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXmvrhMx');
