<?php

namespace ContainerVzuyvFk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtTranslationWpCommentsRepositoryService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\Repository\ExtTranslationWpCommentsRepository' shared autowired service.
     *
     * @return \App\Repository\ExtTranslationWpCommentsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/src/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/LazyServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ExtTranslationWpCommentsRepository.php';

        return $container->privates['App\\Repository\\ExtTranslationWpCommentsRepository'] = new \App\Repository\ExtTranslationWpCommentsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
