<?php

namespace ContainerVzuyvFk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarketingControllerService extends App_KernelRecDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Marketing\MarketingController' shared autowired service.
     *
     * @return \App\Controller\Admin\Marketing\MarketingController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Marketing/MarketingController.php';

        $container->services['App\\Controller\\Admin\\Marketing\\MarketingController'] = $instance = new \App\Controller\Admin\Marketing\MarketingController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->privates['App\\Service\\Payment'] ?? $container->load('getPaymentService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Admin\\Marketing\\MarketingController', $container));

        return $instance;
    }
}
