<?php

namespace ContainerVzuyvFk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceManagerService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\Service\ServiceManager' shared autowired service.
     *
     * @return \App\Service\ServiceManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/ServiceManager.php';

        return $container->privates['App\\Service\\ServiceManager'] = new \App\Service\ServiceManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
