<?php

namespace ContainerVzuyvFk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getToolsMetaControllerService extends App_KernelRecDebugContainer
{
    /**
     * Gets the public 'App\Controller\ToolsMetaController' shared autowired service.
     *
     * @return \App\Controller\ToolsMetaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ToolsMetaController.php';

        $container->services['App\\Controller\\ToolsMetaController'] = $instance = new \App\Controller\ToolsMetaController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ToolsMetaController', $container));

        return $instance;
    }
}
