<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class WpPosts extends \App\Entity\WpPosts implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'id', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postAuthor', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postDate', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postDateGmt', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postContent', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postTitle', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postExcerpt', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postStatus', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'commentStatus', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'pingStatus', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postPassword', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postName', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'toPing', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'pinged', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postModified', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postModifiedGmt', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postContentFiltered', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postParent', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'guid', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'menuOrder', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postType', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postMimeType', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'commentCount', 'termTaxonomyId', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'extTranslationWpPosts'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'id', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postAuthor', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postDate', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postDateGmt', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postContent', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postTitle', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postExcerpt', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postStatus', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'commentStatus', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'pingStatus', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postPassword', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postName', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'toPing', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'pinged', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postModified', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postModifiedGmt', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postContentFiltered', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postParent', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'guid', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'menuOrder', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postType', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'postMimeType', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'commentCount', 'termTaxonomyId', '' . "\0" . 'App\\Entity\\WpPosts' . "\0" . 'extTranslationWpPosts'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (WpPosts $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostAuthor(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostAuthor', []);

        return parent::getPostAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostAuthor(int $postAuthor): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostAuthor', [$postAuthor]);

        return parent::setPostAuthor($postAuthor);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDate', []);

        return parent::getPostDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDate(\DateTimeInterface $postDate): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDate', [$postDate]);

        return parent::setPostDate($postDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostDateGmt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostDateGmt', []);

        return parent::getPostDateGmt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostDateGmt(\DateTimeInterface $postDateGmt): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostDateGmt', [$postDateGmt]);

        return parent::setPostDateGmt($postDateGmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostContent(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostContent', []);

        return parent::getPostContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostContent(string $postContent): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostContent', [$postContent]);

        return parent::setPostContent($postContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostTitle', []);

        return parent::getPostTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostTitle(string $postTitle): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostTitle', [$postTitle]);

        return parent::setPostTitle($postTitle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostExcerpt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostExcerpt', []);

        return parent::getPostExcerpt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostExcerpt(string $postExcerpt): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostExcerpt', [$postExcerpt]);

        return parent::setPostExcerpt($postExcerpt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostStatus', []);

        return parent::getPostStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostStatus(string $postStatus): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostStatus', [$postStatus]);

        return parent::setPostStatus($postStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentStatus', []);

        return parent::getCommentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentStatus(string $commentStatus): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentStatus', [$commentStatus]);

        return parent::setCommentStatus($commentStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPingStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPingStatus', []);

        return parent::getPingStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPingStatus(string $pingStatus): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPingStatus', [$pingStatus]);

        return parent::setPingStatus($pingStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostPassword', []);

        return parent::getPostPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostPassword(string $postPassword): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostPassword', [$postPassword]);

        return parent::setPostPassword($postPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostName', []);

        return parent::getPostName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostName(string $postName): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostName', [$postName]);

        return parent::setPostName($postName);
    }

    /**
     * {@inheritDoc}
     */
    public function getToPing(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getToPing', []);

        return parent::getToPing();
    }

    /**
     * {@inheritDoc}
     */
    public function setToPing(string $toPing): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setToPing', [$toPing]);

        return parent::setToPing($toPing);
    }

    /**
     * {@inheritDoc}
     */
    public function getPinged(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPinged', []);

        return parent::getPinged();
    }

    /**
     * {@inheritDoc}
     */
    public function setPinged(string $pinged): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPinged', [$pinged]);

        return parent::setPinged($pinged);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostModified(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostModified', []);

        return parent::getPostModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostModified(\DateTimeInterface $postModified): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostModified', [$postModified]);

        return parent::setPostModified($postModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostModifiedGmt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostModifiedGmt', []);

        return parent::getPostModifiedGmt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostModifiedGmt(\DateTimeInterface $postModifiedGmt): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostModifiedGmt', [$postModifiedGmt]);

        return parent::setPostModifiedGmt($postModifiedGmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostContentFiltered(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostContentFiltered', []);

        return parent::getPostContentFiltered();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostContentFiltered(string $postContentFiltered): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostContentFiltered', [$postContentFiltered]);

        return parent::setPostContentFiltered($postContentFiltered);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostParent(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostParent', []);

        return parent::getPostParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostParent(int $postParent): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostParent', [$postParent]);

        return parent::setPostParent($postParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getGuid(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGuid', []);

        return parent::getGuid();
    }

    /**
     * {@inheritDoc}
     */
    public function setGuid(string $guid): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGuid', [$guid]);

        return parent::setGuid($guid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMenuOrder(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMenuOrder', []);

        return parent::getMenuOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setMenuOrder(int $menuOrder): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMenuOrder', [$menuOrder]);

        return parent::setMenuOrder($menuOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostType', []);

        return parent::getPostType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostType(string $postType): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostType', [$postType]);

        return parent::setPostType($postType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostMimeType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostMimeType', []);

        return parent::getPostMimeType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostMimeType(string $postMimeType): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostMimeType', [$postMimeType]);

        return parent::setPostMimeType($postMimeType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentCount(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentCount', []);

        return parent::getCommentCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentCount(string $commentCount): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentCount', [$commentCount]);

        return parent::setCommentCount($commentCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermTaxonomyId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermTaxonomyId', []);

        return parent::getTermTaxonomyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermTaxonomyId(int $termTaxonomyId): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermTaxonomyId', [$termTaxonomyId]);

        return parent::setTermTaxonomyId($termTaxonomyId);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtTranslationWpPosts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtTranslationWpPosts', []);

        return parent::getExtTranslationWpPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function addExtTranslationWpPost(\App\Entity\ExtTranslationWpPosts $extTranslationWpPost): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExtTranslationWpPost', [$extTranslationWpPost]);

        return parent::addExtTranslationWpPost($extTranslationWpPost);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExtTranslationWpPost(\App\Entity\ExtTranslationWpPosts $extTranslationWpPost): \App\Entity\WpPosts
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExtTranslationWpPost', [$extTranslationWpPost]);

        return parent::removeExtTranslationWpPost($extTranslationWpPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getReservationPriceTtc(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReservationPriceTtc', []);

        return parent::getReservationPriceTtc();
    }

}
