<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6fg1Euc\App_KernelRecDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6fg1Euc/App_KernelRecDebugContainer.php') {
    touch(__DIR__.'/Container6fg1Euc.legacy');

    return;
}

if (!\class_exists(App_KernelRecDebugContainer::class, false)) {
    \class_alias(\Container6fg1Euc\App_KernelRecDebugContainer::class, App_KernelRecDebugContainer::class, false);
}

return new \Container6fg1Euc\App_KernelRecDebugContainer([
    'container.build_hash' => '6fg1Euc',
    'container.build_id' => 'e4b87ef5',
    'container.build_time' => 1748469993,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6fg1Euc');
