<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonnementsCsvExporterService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\Service\Export\AbonnementsCsvExporter' shared autowired service.
     *
     * @return \App\Service\Export\AbonnementsCsvExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Export/AbonnementsCsvExporter.php';

        return $container->privates['App\\Service\\Export\\AbonnementsCsvExporter'] = new \App\Service\Export\AbonnementsCsvExporter(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
