<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleController2Service extends App_KernelRecDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Articles\ArticleController' shared autowired service.
     *
     * @return \App\Controller\Admin\Articles\ArticleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Articles/ArticleController.php';

        $container->services['App\\Controller\\Admin\\Articles\\ArticleController'] = $instance = new \App\Controller\Admin\Articles\ArticleController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Admin\\Articles\\ArticleController', $container));

        return $instance;
    }
}
