<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbonnementPrePersistService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\EventListener\AbonnementPrePersist' shared autowired service.
     *
     * @return \App\EventListener\AbonnementPrePersist
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/AbonnementPrePersist.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        if (isset($container->privates['App\\EventListener\\AbonnementPrePersist'])) {
            return $container->privates['App\\EventListener\\AbonnementPrePersist'];
        }

        return $container->privates['App\\EventListener\\AbonnementPrePersist'] = new \App\EventListener\AbonnementPrePersist($a);
    }
}
