<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvCommandesExporterService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\Service\Export\CsvCommandesExporter' shared autowired service.
     *
     * @return \App\Service\Export\CsvCommandesExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Export/CsvCommandesExporter.php';

        return $container->privates['App\\Service\\Export\\CsvCommandesExporter'] = new \App\Service\Export\CsvCommandesExporter(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')));
    }
}
