<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartementPreRemoveService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\EventListener\DepartementPreRemove' shared autowired service.
     *
     * @return \App\EventListener\DepartementPreRemove
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/DepartementPreRemove.php';

        return $container->privates['App\\EventListener\\DepartementPreRemove'] = new \App\EventListener\DepartementPreRemove();
    }
}
