<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getErrorControllerService extends App_KernelRecDebugContainer
{
    /**
     * Gets the public 'App\Controller\ErrorController' shared autowired service.
     *
     * @return \App\Controller\ErrorController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/ErrorController.php';

        return $container->services['App\\Controller\\ErrorController'] = new \App\Controller\ErrorController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), true);
    }
}
