<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParcoursUtilisateurControllerService extends App_KernelRecDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\ParcoursUtilisateur\ParcoursUtilisateurController' shared autowired service.
     *
     * @return \App\Controller\Admin\ParcoursUtilisateur\ParcoursUtilisateurController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/ParcoursUtilisateur/ParcoursUtilisateurController.php';

        $container->services['App\\Controller\\Admin\\ParcoursUtilisateur\\ParcoursUtilisateurController'] = $instance = new \App\Controller\Admin\ParcoursUtilisateur\ParcoursUtilisateurController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), (isset($container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']) ? $container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']() : $container->getAdminUrlGeneratorService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Admin\\ParcoursUtilisateur\\ParcoursUtilisateurController', $container));

        return $instance;
    }
}
