<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecaptchaService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\Service\Recaptcha\Recaptcha' shared autowired service.
     *
     * @return \App\Service\Recaptcha\Recaptcha
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Recaptcha/Recaptcha.php';

        return $container->privates['App\\Service\\Recaptcha\\Recaptcha'] = new \App\Service\Recaptcha\Recaptcha();
    }
}
