<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPreUpdateService extends App_KernelRecDebugContainer
{
    /**
     * Gets the private 'App\EventListener\UserPreUpdate' shared autowired service.
     *
     * @return \App\EventListener\UserPreUpdate
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/UserPreUpdate.php';

        return $container->privates['App\\EventListener\\UserPreUpdate'] = new \App\EventListener\UserPreUpdate();
    }
}
