<?php

namespace Container6fg1Euc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWpPostsCrudController7Service extends App_KernelRecDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\Livraisons\OpeFraisGratuits\WpPostsCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\Livraisons\OpeFraisGratuits\WpPostsCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/CrudControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractCrudController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/Livraisons/OpeFraisGratuits/WpPostsCrudController.php';

        $container->services['App\\Controller\\Admin\\Livraisons\\OpeFraisGratuits\\WpPostsCrudController'] = $instance = new \App\Controller\Admin\Livraisons\OpeFraisGratuits\WpPostsCrudController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), (isset($container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']) ? $container->factories['service_container']['EasyCorp\\Bundle\\EasyAdminBundle\\Router\\AdminUrlGenerator']() : $container->getAdminUrlGeneratorService()));

        $instance->setContainer(($container->privates['.service_locator.UIrHhwh'] ?? $container->load('get_ServiceLocator_UIrHhwhService'))->withContext('App\\Controller\\Admin\\Livraisons\\OpeFraisGratuits\\WpPostsCrudController', $container));

        return $instance;
    }
}
