<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KJH4MstService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.KJH4Mst' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KJH4Mst'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'recaptcha' => ['privates', 'App\\Service\\Recaptcha\\Recaptcha', 'getRecaptchaService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'mailer' => '?',
            'recaptcha' => 'App\\Service\\Recaptcha\\Recaptcha',
            'translator' => '?',
        ]);
    }
}
