<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EPNKy3FService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ePNKy3F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ePNKy3F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'user' => ['privates', '.errored..service_locator.ePNKy3F.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.ePNKy3F": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
