<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LUYhi3IService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.lUYhi3I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lUYhi3I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recaptcha' => ['privates', 'App\\Service\\Recaptcha\\Recaptcha', 'getRecaptchaService', true],
        ], [
            'recaptcha' => 'App\\Service\\Recaptcha\\Recaptcha',
        ]);
    }
}
