<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnoncesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\DataAccessLayer\Annonces' shared autowired service.
     *
     * @return \App\Service\DataAccessLayer\Annonces
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\DataAccessLayer\\Annonces'] = new \App\Service\DataAccessLayer\Annonces(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')));
    }
}
