<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\ArticleController' shared autowired service.
     *
     * @return \App\Controller\Admin\ArticleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\ArticleController'] = $instance = new \App\Controller\Admin\ArticleController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Admin\\ArticleController', $container));

        return $instance;
    }
}
