<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnoncesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\AnnoncesController' shared autowired service.
     *
     * @return \App\Controller\AnnoncesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\AnnoncesController'] = $instance = new \App\Controller\AnnoncesController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->privates['App\\Service\\DataAccessLayer\\Annonces'] ?? $container->load('getAnnoncesService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\ToolsMeta'] ?? $container->load('getToolsMetaService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['App\\Service\\Panier'] ?? ($container->privates['App\\Service\\Panier'] = new \App\Service\Panier())));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\AnnoncesController', $container));

        return $instance;
    }
}
