<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AppAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AppAuthenticator'] = new \App\Security\AppAuthenticator(($container->services['router'] ?? $container->getRouterService()), ($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\Recaptcha\\Recaptcha'] ?? ($container->privates['App\\Service\\Recaptcha\\Recaptcha'] = new \App\Service\Recaptcha\Recaptcha())));
    }
}
