<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnnonceAdminControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\Annonces\AnnonceAdminController' shared autowired service.
     *
     * @return \App\Controller\Admin\Annonces\AnnonceAdminController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\Annonces\\AnnonceAdminController'] = $instance = new \App\Controller\Admin\Annonces\AnnonceAdminController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\Admin\\Annonces\\AnnonceAdminController', $container));

        return $instance;
    }
}
