<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlameableListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Gedmo\Blameable\BlameableListener' shared service.
     *
     * @return \Gedmo\Blameable\BlameableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['Gedmo\\Blameable\\BlameableListener'] = $instance = new \Gedmo\Blameable\BlameableListener();

        $instance->setAnnotationReader(($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()));

        return $instance;
    }
}
