<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvExporterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Export\CsvExporter' shared autowired service.
     *
     * @return \App\Service\Export\CsvExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Export\\CsvExporter'] = new \App\Service\Export\CsvExporter(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
