<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvCommandesExporterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Export\CsvCommandesExporter' shared autowired service.
     *
     * @return \App\Service\Export\CsvCommandesExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Export\\CsvCommandesExporter'] = new \App\Service\Export\CsvCommandesExporter(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')));
    }
}
