<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConversionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ConversionController' shared autowired service.
     *
     * @return \App\Controller\ConversionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ConversionController'] = $instance = new \App\Controller\ConversionController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\ConversionController', $container));

        return $instance;
    }
}
