<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepartementPreRemoveService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\DepartementPreRemove' shared autowired service.
     *
     * @return \App\EventListener\DepartementPreRemove
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\EventListener\\DepartementPreRemove'] = new \App\EventListener\DepartementPreRemove();
    }
}
