<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDevisControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\DevisController' shared autowired service.
     *
     * @return \App\Controller\DevisController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\DevisController'] = $instance = new \App\Controller\DevisController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\DataAccessLayer\\Annonces'] ?? $container->load('getAnnoncesService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['App\\Service\\Payment'] ?? $container->load('getPaymentService')), ($container->privates['App\\Service\\Panier'] ?? ($container->privates['App\\Service\\Panier'] = new \App\Service\Panier())), ($container->privates['App\\Service\\ToolsMeta'] ?? $container->load('getToolsMetaService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\DevisController', $container));

        return $instance;
    }
}
