<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExtTranslationWpTermTaxonomyRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ExtTranslationWpTermTaxonomyRepository' shared autowired service.
     *
     * @return \App\Repository\ExtTranslationWpTermTaxonomyRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ExtTranslationWpTermTaxonomyRepository'] = new \App\Repository\ExtTranslationWpTermTaxonomyRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
