<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInformationsFacturationUtilisateurRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\InformationsFacturationUtilisateurRepository' shared autowired service.
     *
     * @return \App\Repository\InformationsFacturationUtilisateurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\InformationsFacturationUtilisateurRepository'] = new \App\Repository\InformationsFacturationUtilisateurRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
