<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarketingController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\MarketingController' shared autowired service.
     *
     * @return \App\Controller\MarketingController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\MarketingController'] = $instance = new \App\Controller\MarketingController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->privates['App\\Service\\ToolsMeta'] ?? $container->load('getToolsMetaService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\MarketingController', $container));

        return $instance;
    }
}
