<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOffreInterneCrudControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\Configurations\OffreInterneCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\Configurations\OffreInterneCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\Configurations\\OffreInterneCrudController'] = $instance = new \App\Controller\Admin\Configurations\OffreInterneCrudController();

        $instance->setContainer(($container->privates['.service_locator.UIrHhwh'] ?? $container->load('get_ServiceLocator_UIrHhwhService'))->withContext('App\\Controller\\Admin\\Configurations\\OffreInterneCrudController', $container));

        return $instance;
    }
}
