<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_View_DefaultService extends App_KernelProdContainer
{
    /*
     * Gets the private 'pagerfanta.view.default' shared service.
     *
     * @return \Pagerfanta\View\DefaultView
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['pagerfanta.view.default'] = new \Pagerfanta\View\DefaultView();
    }
}
