<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PaymentController' shared autowired service.
     *
     * @return \App\Controller\PaymentController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PaymentController'] = $instance = new \App\Controller\PaymentController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->privates['App\\Service\\ToolsMeta'] ?? $container->load('getToolsMetaService')), ($container->privates['App\\Service\\Payment'] ?? $container->load('getPaymentService')), ($container->privates['App\\Service\\Panier'] ?? ($container->privates['App\\Service\\Panier'] = new \App\Service\Panier())), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\PaymentController', $container));

        return $instance;
    }
}
