<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_View_TwitterBootstrapService extends App_KernelProdContainer
{
    /*
     * Gets the private 'pagerfanta.view.twitter_bootstrap' shared service.
     *
     * @return \Pagerfanta\View\TwitterBootstrapView
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['pagerfanta.view.twitter_bootstrap'] = new \Pagerfanta\View\TwitterBootstrapView();
    }
}
