<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_View_TwitterBootstrap3Service extends App_KernelProdContainer
{
    /*
     * Gets the private 'pagerfanta.view.twitter_bootstrap3' shared service.
     *
     * @return \Pagerfanta\View\TwitterBootstrap3View
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['pagerfanta.view.twitter_bootstrap3'] = new \Pagerfanta\View\TwitterBootstrap3View();
    }
}
