<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerfanta_View_TwigService extends App_KernelProdContainer
{
    /*
     * Gets the private 'pagerfanta.view.twig' shared service.
     *
     * @return \Pagerfanta\Twig\View\TwigView
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService());

        if (isset($container->privates['pagerfanta.view.twig'])) {
            return $container->privates['pagerfanta.view.twig'];
        }

        return $container->privates['pagerfanta.view.twig'] = new \Pagerfanta\Twig\View\TwigView($a, '@BabDevPagerfanta/twitter_bootstrap5.html.twig');
    }
}
