<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaymentService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Payment' shared autowired service.
     *
     * @return \App\Service\Payment
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Payment'] = new \App\Service\Payment(($container->privates['http_client'] ?? $container->load('getHttpClientService')));
    }
}
