<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getServiceManagerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ServiceManager' shared autowired service.
     *
     * @return \App\Service\ServiceManager
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ServiceManager'] = new \App\Service\ServiceManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
