<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSouscriptionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\SouscriptionController' shared autowired service.
     *
     * @return \App\Controller\SouscriptionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\SouscriptionController'] = $instance = new \App\Controller\SouscriptionController(($container->privates['App\\Service\\ServiceManager'] ?? $container->load('getServiceManagerService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['.container.private.twig'] ?? $container->get_Container_Private_TwigService()), ($container->privates['App\\Service\\Payment'] ?? $container->load('getPaymentService')));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\SouscriptionController', $container));

        return $instance;
    }
}
