<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWpTermsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\WpTermsRepository' shared autowired service.
     *
     * @return \App\Repository\WpTermsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\WpTermsRepository'] = new \App\Repository\WpTermsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
