<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWpTermRelationshipsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\WpTermRelationshipsRepository' shared autowired service.
     *
     * @return \App\Repository\WpTermRelationshipsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\WpTermRelationshipsRepository'] = new \App\Repository\WpTermRelationshipsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
