<?php

namespace ContainerXmvrhMx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWpPostsCrudController14Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Admin\PagesStatiques\WpPostsCrudController' shared autowired service.
     *
     * @return \App\Controller\Admin\PagesStatiques\WpPostsCrudController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\PagesStatiques\\WpPostsCrudController'] = $instance = new \App\Controller\Admin\PagesStatiques\WpPostsCrudController();

        $instance->setContainer(($container->privates['.service_locator.UIrHhwh'] ?? $container->load('get_ServiceLocator_UIrHhwhService'))->withContext('App\\Controller\\Admin\\PagesStatiques\\WpPostsCrudController', $container));

        return $instance;
    }
}
