<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userNicename', '' . "\0" . 'App\\Entity\\User' . "\0" . 'usernameCanonical', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userRegistered', '' . "\0" . 'App\\Entity\\User' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userActivationKey', '' . "\0" . 'App\\Entity\\User' . "\0" . 'displayName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'landingPage', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userStatus', '' . "\0" . 'App\\Entity\\User' . "\0" . 'enabled', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lastActivityAt', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sentMessages', '' . "\0" . 'App\\Entity\\User' . "\0" . 'receivedMessages', '' . "\0" . 'App\\Entity\\User' . "\0" . 'channels1', '' . "\0" . 'App\\Entity\\User' . "\0" . 'channels2', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email_canonical', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'isVerified', '' . "\0" . 'App\\Entity\\User' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userUniqueData', '' . "\0" . 'App\\Entity\\User' . "\0" . 'abonnements', '' . "\0" . 'App\\Entity\\User' . "\0" . 'informationsFacturationUtilisateur'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\User' . "\0" . 'id', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userNicename', '' . "\0" . 'App\\Entity\\User' . "\0" . 'usernameCanonical', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userRegistered', '' . "\0" . 'App\\Entity\\User' . "\0" . 'updatedAt', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userActivationKey', '' . "\0" . 'App\\Entity\\User' . "\0" . 'displayName', '' . "\0" . 'App\\Entity\\User' . "\0" . 'landingPage', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userStatus', '' . "\0" . 'App\\Entity\\User' . "\0" . 'enabled', '' . "\0" . 'App\\Entity\\User' . "\0" . 'lastActivityAt', '' . "\0" . 'App\\Entity\\User' . "\0" . 'sentMessages', '' . "\0" . 'App\\Entity\\User' . "\0" . 'receivedMessages', '' . "\0" . 'App\\Entity\\User' . "\0" . 'channels1', '' . "\0" . 'App\\Entity\\User' . "\0" . 'channels2', '' . "\0" . 'App\\Entity\\User' . "\0" . 'email_canonical', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userEmail', '' . "\0" . 'App\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\User' . "\0" . 'password', '' . "\0" . 'App\\Entity\\User' . "\0" . 'isVerified', '' . "\0" . 'App\\Entity\\User' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\User' . "\0" . 'userUniqueData', '' . "\0" . 'App\\Entity\\User' . "\0" . 'abonnements', '' . "\0" . 'App\\Entity\\User' . "\0" . 'informationsFacturationUtilisateur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', []);

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical(string $email_canonical): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', [$email_canonical]);

        return parent::setEmailCanonical($email_canonical);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function isVerified(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVerified', []);

        return parent::isVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVerified(bool $isVerified): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVerified', [$isVerified]);

        return parent::setIsVerified($isVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', []);

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical(string $usernameCanonical): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', [$usernameCanonical]);

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserRegistered(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserRegistered', []);

        return parent::getUserRegistered();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserRegistered(string $userRegistered): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserRegistered', [$userRegistered]);

        return parent::setUserRegistered($userRegistered);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserActivationKey(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserActivationKey', []);

        return parent::getUserActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserActivationKey(string $userActivationKey): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserActivationKey', [$userActivationKey]);

        return parent::setUserActivationKey($userActivationKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserNicename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserNicename', []);

        return parent::getUserNicename();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserNicename(string $userNicename): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserNicename', [$userNicename]);

        return parent::setUserNicename($userNicename);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayName', []);

        return parent::getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayName(string $displayName): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayName', [$displayName]);

        return parent::setDisplayName($displayName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', []);

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled(int $enabled): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$enabled]);

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserEmail', []);

        return parent::getUserEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserEmail(string $userEmail): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserEmail', [$userEmail]);

        return parent::setUserEmail($userEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserStatus', []);

        return parent::getUserStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserStatus(string $userStatus): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserStatus', [$userStatus]);

        return parent::setUserStatus($userStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(?string $dateNaissance): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastActivityAt(\DateTime $lastActivityAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastActivityAt', [$lastActivityAt]);

        return parent::setLastActivityAt($lastActivityAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastActivityAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastActivityAt', []);

        return parent::getLastActivityAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isActiveNow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActiveNow', []);

        return parent::isActiveNow();
    }

    /**
     * {@inheritDoc}
     */
    public function getSentMessages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSentMessages', []);

        return parent::getSentMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function getReceivedMessages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceivedMessages', []);

        return parent::getReceivedMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUniqueData(): ?\App\Entity\UserUniqueData
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUniqueData', []);

        return parent::getUserUniqueData();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUniqueData(\App\Entity\UserUniqueData $userUniqueData): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUniqueData', [$userUniqueData]);

        return parent::setUserUniqueData($userUniqueData);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbonnements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbonnements', []);

        return parent::getAbonnements();
    }

    /**
     * {@inheritDoc}
     */
    public function addAbonnement(\App\Entity\Abonnement $abonnement): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAbonnement', [$abonnement]);

        return parent::addAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAbonnement(\App\Entity\Abonnement $abonnement): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAbonnement', [$abonnement]);

        return parent::removeAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function getInformationsFacturationUtilisateur(): ?\App\Entity\InformationsFacturationUtilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInformationsFacturationUtilisateur', []);

        return parent::getInformationsFacturationUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setInformationsFacturationUtilisateur(\App\Entity\InformationsFacturationUtilisateur $informationsFacturationUtilisateur): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInformationsFacturationUtilisateur', [$informationsFacturationUtilisateur]);

        return parent::setInformationsFacturationUtilisateur($informationsFacturationUtilisateur);
    }

}
