<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UserUniqueData extends \App\Entity\UserUniqueData implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'user', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'nomCommercial', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'departement', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'lastName', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'bdaytime', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'nationalityCountry', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'residenceCountry', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'billingEmail', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'raisonSociale', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'postCode', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'siret', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'paysDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'numeroNomRueDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'codePostalDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'villeDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'paysLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'numeroNomRueLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'codePostalLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'villeLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'mp_user_card_id'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'user', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'nomCommercial', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'departement', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'lastName', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'bdaytime', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'nationalityCountry', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'residenceCountry', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'billingEmail', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'raisonSociale', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'postCode', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'siret', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'paysDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'numeroNomRueDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'codePostalDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'villeDomicile', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'paysLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'numeroNomRueLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'codePostalLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'villeLivraison', '' . "\0" . 'App\\Entity\\UserUniqueData' . "\0" . 'mp_user_card_id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UserUniqueData $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Entity\User $user): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomCommercial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomCommercial', []);

        return parent::getNomCommercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomCommercial(?string $nomCommercial): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomCommercial', [$nomCommercial]);

        return parent::setNomCommercial($nomCommercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartement(): ?\App\Entity\Departement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartement', []);

        return parent::getDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartement(?\App\Entity\Departement $departement): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartement', [$departement]);

        return parent::setDepartement($departement);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName(?string $lastName): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName(?string $firstName): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBdaytime(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBdaytime', []);

        return parent::getBdaytime();
    }

    /**
     * {@inheritDoc}
     */
    public function setBdaytime(?string $bdaytime): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBdaytime', [$bdaytime]);

        return parent::setBdaytime($bdaytime);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(?string $sexe): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalityCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalityCountry', []);

        return parent::getNationalityCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalityCountry(?string $nationalityCountry): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalityCountry', [$nationalityCountry]);

        return parent::setNationalityCountry($nationalityCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getResidenceCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResidenceCountry', []);

        return parent::getResidenceCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setResidenceCountry(?string $residenceCountry): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResidenceCountry', [$residenceCountry]);

        return parent::setResidenceCountry($residenceCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingEmail', []);

        return parent::getBillingEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingEmail(?string $billingEmail): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingEmail', [$billingEmail]);

        return parent::setBillingEmail($billingEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(?string $telephone): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSociale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSociale', []);

        return parent::getRaisonSociale();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSociale(?string $raisonSociale): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSociale', [$raisonSociale]);

        return parent::setRaisonSociale($raisonSociale);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostCode', []);

        return parent::getPostCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostCode(?string $postCode): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostCode', [$postCode]);

        return parent::setPostCode($postCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiret(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiret', []);

        return parent::getSiret();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiret(?string $siret): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiret', [$siret]);

        return parent::setSiret($siret);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysDomicile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysDomicile', []);

        return parent::getPaysDomicile();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysDomicile(?string $paysDomicile): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysDomicile', [$paysDomicile]);

        return parent::setPaysDomicile($paysDomicile);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroNomRueDomicile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroNomRueDomicile', []);

        return parent::getNumeroNomRueDomicile();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroNomRueDomicile(?string $numeroNomRueDomicile): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroNomRueDomicile', [$numeroNomRueDomicile]);

        return parent::setNumeroNomRueDomicile($numeroNomRueDomicile);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostalDomicile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostalDomicile', []);

        return parent::getCodePostalDomicile();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostalDomicile(?string $codePostalDomicile): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostalDomicile', [$codePostalDomicile]);

        return parent::setCodePostalDomicile($codePostalDomicile);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleDomicile(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleDomicile', []);

        return parent::getVilleDomicile();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleDomicile(?string $villeDomicile): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleDomicile', [$villeDomicile]);

        return parent::setVilleDomicile($villeDomicile);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaysLivraison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaysLivraison', []);

        return parent::getPaysLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaysLivraison(?string $paysLivraison): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaysLivraison', [$paysLivraison]);

        return parent::setPaysLivraison($paysLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroNomRueLivraison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroNomRueLivraison', []);

        return parent::getNumeroNomRueLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroNomRueLivraison(?string $numeroNomRueLivraison): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroNomRueLivraison', [$numeroNomRueLivraison]);

        return parent::setNumeroNomRueLivraison($numeroNomRueLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostalLivraison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostalLivraison', []);

        return parent::getCodePostalLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostalLivraison(?string $codePostalLivraison): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostalLivraison', [$codePostalLivraison]);

        return parent::setCodePostalLivraison($codePostalLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleLivraison(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleLivraison', []);

        return parent::getVilleLivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleLivraison(?string $villeLivraison): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleLivraison', [$villeLivraison]);

        return parent::setVilleLivraison($villeLivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getMpUserCardId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMpUserCardId', []);

        return parent::getMpUserCardId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMpUserCardId(?string $mp_user_card_id): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMpUserCardId', [$mp_user_card_id]);

        return parent::setMpUserCardId($mp_user_card_id);
    }

}
