<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OffreInterne extends \App\Entity\OffreInterne implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'descriptif', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'tarif', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'locale', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'abonnements', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'creerAnnonce', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'creerDevis', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'referencement', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'packsProduction', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'enteteDescriptif', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'id', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'descriptif', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'tarif', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'slug', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'locale', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'abonnements', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'creerAnnonce', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'creerDevis', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'referencement', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'packsProduction', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'enteteDescriptif', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\OffreInterne' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OffreInterne $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptif', []);

        return parent::getDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptif(?string $descriptif): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptif', [$descriptif]);

        return parent::setDescriptif($descriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', []);

        return parent::getTarif();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarif(float $tarif): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarif', [$tarif]);

        return parent::setTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setTranslatableLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTranslatableLocale', [$locale]);

        return parent::setTranslatableLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbonnements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbonnements', []);

        return parent::getAbonnements();
    }

    /**
     * {@inheritDoc}
     */
    public function addAbonnement(\App\Entity\Abonnement $abonnement): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAbonnement', [$abonnement]);

        return parent::addAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAbonnement(\App\Entity\Abonnement $abonnement): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAbonnement', [$abonnement]);

        return parent::removeAbonnement($abonnement);
    }

    /**
     * {@inheritDoc}
     */
    public function isCreerAnnonce(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCreerAnnonce', []);

        return parent::isCreerAnnonce();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreerAnnonce(?bool $creerAnnonce): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreerAnnonce', [$creerAnnonce]);

        return parent::setCreerAnnonce($creerAnnonce);
    }

    /**
     * {@inheritDoc}
     */
    public function isCreerDevis(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCreerDevis', []);

        return parent::isCreerDevis();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreerDevis(?bool $creerDevis): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreerDevis', [$creerDevis]);

        return parent::setCreerDevis($creerDevis);
    }

    /**
     * {@inheritDoc}
     */
    public function isReferencement(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isReferencement', []);

        return parent::isReferencement();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferencement(?bool $referencement): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferencement', [$referencement]);

        return parent::setReferencement($referencement);
    }

    /**
     * {@inheritDoc}
     */
    public function isPacksProduction(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPacksProduction', []);

        return parent::isPacksProduction();
    }

    /**
     * {@inheritDoc}
     */
    public function setPacksProduction(?bool $packsProduction): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPacksProduction', [$packsProduction]);

        return parent::setPacksProduction($packsProduction);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnteteDescriptif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnteteDescriptif', []);

        return parent::getEnteteDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnteteDescriptif(?string $enteteDescriptif): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnteteDescriptif', [$enteteDescriptif]);

        return parent::setEnteteDescriptif($enteteDescriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

}
